// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retroboard.Api.Infrastructure.Data;

#nullable disable

namespace Retroboard.Api.Migrations
{
    [DbContext(typeof(RetroboardDbContext))]
    partial class RetroboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Board", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InviteRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Card", b =>
                {
                    b.Property<string>("BoardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColumnId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("BoardId", "ColumnId", "Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Column", b =>
                {
                    b.Property<string>("BoardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoardId", "Id");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Comment", b =>
                {
                    b.Property<string>("BoardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColumnId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoardId", "ColumnId", "CardId", "Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Card", b =>
                {
                    b.HasOne("Retroboard.Api.Domain.Entities.Column", "Column")
                        .WithMany("Cards")
                        .HasForeignKey("BoardId", "ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Column", b =>
                {
                    b.HasOne("Retroboard.Api.Domain.Entities.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Retroboard.Api.Domain.Entities.Card", "Card")
                        .WithMany("Comments")
                        .HasForeignKey("BoardId", "ColumnId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Participant", b =>
                {
                    b.HasOne("Retroboard.Api.Domain.Entities.Board", "Board")
                        .WithMany("Participants")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Board", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Card", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Retroboard.Api.Domain.Entities.Column", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
